### ISSUE TITLE
Error using updated Roman grism config from Wang et al. 2022a

### ISSUE THREAD

**Issue by Zhiyuan-G** [gbrammer/grizli#170]
Hi, 
I'm trying to simulate Roman grism images with the axesim configuration file used by Wang et al 2022a in [here](https://irsa.ipac.caltech.edu/data/theory/Roman/Wang2022a/products/configuration/). I replaced the trace description and Dispersion solution in `Roman.G150.conf` with the ones from the above link. For some sources, I was getting the following exception error when running `roman_sim.compute_full_model(ids=[...], mags=[...])` 
'''
########################################## 
# ! Exception (2023-09-06 23:50:31.925)
#
# !Traceback (most recent call last):
# !  File "/my/path/to/miniconda3/envs/grizli39/lib/python3.9/site-packages/grizli/model.py", line 419, in process_config
# !    self.flat_index = self.idx[dyc + self.x0[0], self.dxpix]
# !IndexError: index 86 is out of bounds for axis 0 with size 52
# !
# !During handling of the above exception, another exception occurred:
# !
# !Traceback (most recent call last):
# !  File "/my/path/to/miniconda3/envs/grizli39/lib/python3.9/site-packages/grizli/model.py", line 3148, in compute_model_orders
# !    beam = GrismDisperser(id=id,
# !  File "/my/path/to/miniconda3/envs/grizli39/lib/python3.9/site-packages/grizli/model.py", line 289, in __init__
# !    self.process_config()
# !IndexError
# !
'''
Any help will be greatly appreciated! Thank you!

**Comment by gbrammer** [comment]
That can happen if there are spectra that "fall off" the nominal pixel grid of a particular exposure.  Sacrificing generality for a bit of speed, the array index bit that raises the error doesn't do any checking if only a subset of the expected trace is available.  

This issue can usually be fixed by zero-padding the image arrays of the `GrismFLT` object at initialization with `GrismFLT(..., pad=[ny, nx])` where, `nx` is of order the size in pixels of a dispersed spectrum.  `ny > 0` may be necessary if there is a significant cross dispersion offset of the trace.

**Comment by gbrammer** [comment]
OK, now I see that the problem seems to be with a large implied cross-dispersion offset of the trace as defined in your configuration file.  The `size` parameter in [GroupFLT.compute_full_model](https://github.com/gbrammer/grizli/blob/master/grizli/multifit.py#L561) has to be something larger than the trace `dy` offset.  

Currently the indexing is naive in that it assumes `dy` is small and makes a cutout from the grism exposure with the same row slicing as for the direct image.  The [GrismDisperser](https://github.com/gbrammer/grizli/blob/master/grizli/model.py#L124) object could be modified to accept a keyword, or compute itself, an integer offset such that the trace is centered in the grism cutout.

![trace-demo](https://github.com/gbrammer/grizli/assets/1577270/9f311980-84f9-47e6-a3a2-301049743887)

Demo in the attached notebook.

[grizli_Roman_config_issue_example.ipynb.txt](https://github.com/gbrammer/grizli/files/12617647/grizli_Roman_config_issue_example.ipynb.txt)
