### ISSUE TITLE
Website grizli-cutout.herokuapp.com 'cosmos-psf' does not work well

### ISSUE THREAD

**Issue by YoRHazero** [gbrammer/grizli#184]
I want to report an error I meet when I try to download the cosmos-psf on this website: https://grizli-cutout.herokuapp.com/. I am sorry if I reported this issue in the wrong place. 

When I try to download the PSF it reports:
```
Traceback (most recent call last):
File "/app/cosmos_psf.py", line 277, in get_cosmos_psf
from photutils import CosineBellWindow
ModuleNotFoundError: No module named 'photutils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/app/cosmos_psf.py", line 135, in run_cosmos_psf
_tab, hdul, fig = get_cosmos_psf(**kwargs)
ModuleNotFoundError: No module named 'photutils'
```

Could someone help check?

**Comment by gbrammer** [comment]
This should be back up now.
