### ISSUE TITLE
Numpy module not found when installing with requirements.txt

### ISSUE THREAD

**Issue by jkmatharu** [gbrammer/grizli#59]
The following error has occurred for 2 different users when running the following installation line for Grizli: `pip install --editable . -r requirements.txt`

```(grizli-dev) jasleenmatharu2@842b2bbb8b8d:~/src/grizli$ pip install --editable . -r requirements.txt
Obtaining file:///Users/jasleenmatharu2/src/grizli
    ERROR: Command errored out with exit status 1:
     command: /Users/jasleenmatharu2/anaconda3/envs/grizli-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/jasleenmatharu2/src/grizli/setup.py'"'"'; __file__='"'"'/Users/jasleenmatharu2/src/grizli/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/7v/kgmhmyy511lf7pysbymlcpl00000gn/T/pip-pip-egg-info-w07rixgv
         cwd: /Users/jasleenmatharu2/src/grizli/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/jasleenmatharu2/src/grizli/setup.py", line 15, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
WARNING: Discarding file:///Users/jasleenmatharu2/src/grizli. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Eventually solved by first pip installing numpy and then re-running the command.

**Comment by gbrammer** [comment]
Thanks @jkmatharu.  I updated the installation instructions in https://github.com/gbrammer/grizli/commit/4fe3a9f31b9143e85d955192cf689f2a4502c88f to include `numpy` and `cython` when initializing the conda environment.
